version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: dms-calendar
    #entrypoint: [".docker/docker-setup.sh"]
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dms_root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: dms-calendar
  ldap:
    image: osixia/openldap:1.1.8
    ports:
      - "389:389"
